# Generated by Django 5.0.7 on 2024-09-12 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='main_image',
        ),
    ]
